/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DeviceDeviceIdRouteImport } from './routes/device.$deviceId'
import { Route as VerifyBatchIdRouteImport } from './routes/verify.$batchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceDeviceIdRoute = DeviceDeviceIdRouteImport.update({
  id: '/device/$deviceId',
  path: '/device/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyBatchIdRoute = VerifyBatchIdRouteImport.update({
  id: '/verify/$batchId',
  path: '/verify/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alerts' | '/device/$deviceId' | '/verify/$batchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/device/$deviceId' | '/verify/$batchId'
  id: '__root__' | '/' | '/alerts' | '/device/$deviceId' | '/verify/$batchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DeviceDeviceIdRoute: typeof DeviceDeviceIdRoute
  VerifyBatchIdRoute: typeof VerifyBatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$deviceId': {
      id: '/device/$deviceId'
      path: '/device/$deviceId'
      fullPath: '/device/$deviceId'
      preLoaderRoute: typeof DeviceDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$batchId': {
      id: '/verify/$batchId'
      path: '/verify/$batchId'
      fullPath: '/verify/$batchId'
      preLoaderRoute: typeof VerifyBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DeviceDeviceIdRoute: DeviceDeviceIdRoute,
  VerifyBatchIdRoute: VerifyBatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
